name: intake
channels:
  - defaults

dependencies:
  - appdirs
  - python=3.7
  - dask=2.10.1
  - numpy
  - pandas
  - msgpack-python
  - msgpack-numpy
  - requests
  - tornado
  - jinja2
  - python-snappy
  - pyyaml
  - hvplot >=0.5.2
  - panel >=0.8.0
  - bokeh <2.0.0
  - docutils <0.17  # Downgrade docutils to fix missing bullets (https://stackoverflow.com/a/68008428)
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
